name: Jekyll site CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    # schedule a rebuild at 07:01 UTC every wednesday (articles should be published at 09:01 UTC+2)
  schedule:
    - cron: '1 7 * * WED'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:3.8 jekyll build --baseurl /jekyll-site
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: _site
        CLEAN: true
