name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Build the site in the jekyll/builder container
      run: |
        # copy assets from _posts submodule to jekyll assets directory
        mv _posts/assets/* assets/
        sed -i 's|\(!\[.*\](\)|\1{{site.baseurl}}|g' _posts/*.markdown
        
        
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:3.8 jekyll build --future --baseurl /jekyll-site
        
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: _site
        CLEAN: true
